#! /usr/bin/env php

<?php

use WpSyncer\App\Env;
use Symfony\Component\Console\Application;
use WpSyncer\Command\BackupDatabaseCommand;

require 'vendor/autoload.php';

Env::load();

$app = new Application();
$app->add(new BackupDatabaseCommand());

$app->run();
