#! /usr/bin/env php

<?php

use WpSyncer\App\Env;
use Symfony\Component\Console\Application;
use WpSyncer\Command\BackupDatabaseCommand;

$root = dirname(__DIR__);

if (!is_file(sprintf('%s/vendor/autoload.php', $root))) {
	$root = $_composer_autoload_path ?? dirname(__DIR__, 4) . '/.composer/';
}

require sprintf('%s/vendor/autoload.php', $root);

Env::load();

$app = new Application();
$app->add(new BackupDatabaseCommand());

$app->run();
